name: Generate Changelog
on:
  pull_request:
    types:
      - opened

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        run: |
          git log --format='%s' origin/main..HEAD > changelog.md

      - name: Commit Changelog
        run: |
          git add changelog.txt
          git diff-index --quiet HEAD || git commit -m "chore: Update changelog" && git push origin ${{ github.event.pull_request.head.ref }}
