name: Generate Changelog
on:
  pull_request:
    types:
      - opened

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Generate Changelog
        run: |
          git log --format='%s' main..HEAD > changelog.md

      - name: Commit Changelog
        run: |
          git add changelog.md
          git diff-index --quiet HEAD || git commit -m "chore: Update changelog" && git push origin ${{ github.event.pull_request.head.ref }}
